import "../login.css";
import { useEffect, useRef, useState } from "react";
import { useAuth } from "../components/AuthContext";
import { useNavigate } from "react-router-dom";

const Login = () => {
  const userIdRef = useRef();
  const passRef = useRef();
  const [error, setError] = useState("");
  const { login } = useAuth();
  const navigate = useNavigate();

  const handleLogin = (e) => {
    e.preventDefault();
    let userId = userIdRef.current.value;
    let userPassword = passRef.current.value;

    if (userId != "" && userPassword != "") {
      setError("Login information is incorrect, please check and try again");
    } else {
      login();
      navigate("/");
      window.location.reload();
    }
  };

  //   useEffect(() => {}, [userId, password]);

  return (
    <div className="login-body">
      <div className="login-container">
        <div className="login-box">
          <h1 className="login-head">Welcome to our online banking service</h1>
          <h4 className="login-text">
            Please enter your Login ID and a passcode generated by your token.
          </h4>
          <div className="error">{error}</div>
          <form onSubmit={handleLogin}>
            <div className="form-group">
              <label htmlFor="ID">Login ID</label>
              <input ref={userIdRef} type="text" placeholder="Enter Login ID" />
            </div>
            <div className="form-group">
              <label htmlFor="ID">Passcode</label>
              <input type="text" ref={passRef} placeholder="Enter Passcode" />
            </div>
            <h4 className="login-last">
              Please note: we will never ask you to share your password or PIN.
            </h4>
            <button className="submit" type="submit">
              Continue
            </button>
          </form>
        </div>
      </div>
      <div className="support">
        <div className="box">
          <h5>Contact Us</h5>
          <p>
            If you have any questions about your trading account or need
            assistance with the platform, please reach out to our support team
            at 020 7353 4522. We're here to help you 24/7.
          </p>
        </div>
        <div className="box">
          <h5>Security Information</h5>
          <ul>
            <li>
              Your trading session will automatically end if you are inactive
              for more than ten minutes to protect your account.
            </li>
            <li>
              Ensure that you install and regularly update your anti-virus and
              firewall software to safeguard your device.
            </li>
            <li>
              Keep your trading account credentials confidential. We will never
              ask you for your password or sensitive information via email or
              phone.
            </li>
          </ul>
        </div>
        <div className="box">
          <h5>Fraud Prevention</h5>
          <p>
            To learn more about how to protect yourself from fraud in forex
            trading, please refer to your agent.
            <strong>
               fraud prevention resources available on our website.
            </strong>
          </p>
        </div>
      </div>
      <footer className="login-footer">
        <div className="left">© FEDERAL BUREAU OF EXCHANGE 2019 - 2025</div>
        <div className="right">
          Contact|Privacy|Cookies|FSCS|Legal|Cookie Preferences
        </div>
      </footer>
    </div>
  );
};

export default Login;
